config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'conditions/:id/new',     to: 'conditions#new',     as: :new_condition
  post 'conditions/:id/create', to: 'conditions#create'
  get 'conditions/:id/delete',  to: 'conditions#delete'
  
  get 'prizes/',                to: 'prizes#index',       as: :prizes
  get 'prizes/new',             to: 'prizes#new',         as: :new_prize
  post 'prizes/',               to: 'prizes#create',      as: :create_prize
  get 'prizes/:id/edit',        to: 'prizes#edit',        as: :edit_prize
  post 'prizes/:id/update',     to: 'prizes#update'
  get 'prizes/:id/delete',      to: 'prizes#delete'
  
  get '/',                      to: 'subscribers#home'
  post 'subscribers/',           to: 'subscribers#create', as: :subscriber
  root 'subscribers#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audit_log.rb
class AuditLog < ApplicationRecord
  belongs_to :prize
  belongs_to :subscriber, optional: true
  belongs_to :condition
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :subscriber, optional: true
  belongs_to :prize
  has_many :audit_logs

  validates :number, presence: true
  validates :after_num, presence: true
  validates :condition_type, presence: true
  
end

app/models/prize.rb
class Prize < ApplicationRecord
  has_many :conditions
  has_many :audit_logs

  validates :title, presence: true
  validates :description, presence: true
  validates :existences, presence: true
  validates :active, presence: true

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  has_many :conditions
  has_many :audit_logs

  validates :email, presence: true

  after_create do |subscriber|
    # Send and email with all actives prizes
    SubscriberMailer.prize_won(subscriber).deliver_now
  end
end

app/models/user.rb
# :nocov:
class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end
# :nocov:

app/controllers/application_controller.rb
# :nocov:
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end
# :nocov:

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def new
    @prize_id = condition_edit_params["id"].to_i
  end

  def create
    #debugger
    prize = Prize.find_by(id: condition_edit_params[:id].to_i)
    if prize
      @condition = Condition.new(condition_params)
      @condition = prize.conditions.build(@condition.as_json)
      if (condition_params["number"].to_i > 0) && (condition_params["after_num"].to_i >= 0) && @condition.save
        redirect_to prizes_path, flash: { success: 'The condition has been created' }
      else
        redirect_to new_condition_path, flash: { error: 'Invalid params' }
      end
    else
      redirect_to prizes_path, flash: { error: 'Prize not found' }
    end
  end

  def delete
    @condition = Condition.find_by(id: condition_edit_params[:id].to_i)
    if  @condition
      @condition.delete
      redirect_to prizes_path, flash: { alert: 'The condition has been deleted' }
    else
      redirect_to prizes_path, flash: { error: 'Condition not found' }
    end
  end

  private
  def condition_params
    params.permit(:number, :after_num, :condition_type)
  end
  def condition_edit_params
    params.permit(:id)
  end
end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def index
    @prizes = Prize.where(active: true).order(created_at: :asc).limit(100)
  end

  def new
  end

  def create
    @prize = Prize.new(prize_params.merge!({active: true}))
    if (prize_params["existences"].to_i > 0) && @prize.save
      redirect_to prizes_path, flash: { success: 'The prize has been created' }
    else
      redirect_to new_prize_path, flash: { error: 'Invalid params' }
    end
  end

  def edit
    @prize = Prize.find_by(id: prize_edit_params[:id].to_i)
    unless @prize
      redirect_to edit_prize_path, flash: { error: 'Invalid params' }
    end
  end

  def update
    @prize = Prize.find_by(id: prize_edit_params[:id].to_i)
    if validate_prize_params(prize_params)
      redirect_to prizes_path, flash: { alert: 'The prize has been edited' }
    else
      redirect_to edit_prize_path, flash: { error: 'Invalid params' }
    end
  end

  def delete
    @prize = Prize.find_by(id: prize_edit_params[:id].to_i)
    if @prize
      @prize.update_columns(active: false)
      redirect_to prizes_path, flash: { alert: 'The prize has been deleted' }
    else
      redirect_to prizes_path, flash: { error: 'The prize could not been deleted' }
    end
  end

  private
  def prize_params
    params.permit(:title, :description, :existences)
  end
  def prize_edit_params
    params.permit(:id)
  end
  def validate_prize_params(prize_p)
    existence_num = prize_p["existences"].to_i
    if prize_p["title"] && prize_p["description"] && (existence_num.to_i > 0)
      true
    else
      false
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def home
  end

  def create
    @p_subscriber = Subscriber.where(email: subscriber_params["email"]).order(created_at: :desc).first
    subscriber_email = subscriber_params
    if @p_subscriber
      if (@p_subscriber.created_at + 1.day) < Time.now 
        valid_try(subscriber_email)
      else
        redirect_to root_path, flash: { alert: 'This email was already registered today.' }
      end
    else
      valid_try(subscriber_email)
    end 
  end

  private
  def subscriber_params
    params.permit(:email)
  end

  def valid_try(subscriber_email)
    #debugger
    @subscriber = Subscriber.create(subscriber_email)
    Condition.order(created_at: :asc).each do |c_condition|
      if @subscriber.id >= c_condition.after_num
        #debugger
        case c_condition.condition_type
        when "M"
          #debugger
          win_prize(c_condition) if (@subscriber.id % c_condition.number) == 0
        when "S"
          #debugger
          win_prize(c_condition) if c_condition.number == @subscriber.id
        end
      end
    end
    #debugger
    find_prize(@subscriber)
  end
  
  def win_prize(c_condition)
    #debugger
    @audit_log = AuditLog.new({delivered: false})
    @audit_log = c_condition.audit_logs.build(@audit_log.as_json)
    @audit_log = c_condition.prize.audit_logs.build(@audit_log.as_json)
    @audit_log.save
  end

  def find_prize(subscriber)
    #debugger
    audit_log = AuditLog.where(delivered: false).order(created_at: :asc).first
    if audit_log
      #debugger
      subscriber.audit_logs << audit_log
      audit_log.update(delivered: true)
      deliver_prize(audit_log.prize_id)
    else
      #debugger
      redirect_to root_path, flash: { error: 'Try again tomorrow.' }
    end
  end

  def deliver_prize(prize_id)
    #debugger
    prize = Prize.find_by(id: prize_id)
    prize.update(existences: (prize.existences.to_i - 1))
    if prize.existences == "0"
      #debugger
      prize.update_columns(active: false)
    end
    redirect_to root_path, flash: { success: "You won this prize: #{prize.title}, Description: #{prize.description}." }
  end
end

app/helpers/application_helper.rb
# :nocov:
module ApplicationHelper
  def flash_class(type)
    case type
      when :success then "success"
      when :error   then "danger"
      when :alert   then "warning"
      when :notice  then "info"
      else "info"
    end
  end
end
# :nocov:

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/conditions/new.html.erb
<h1>Create a condition</h1>
<div class="container">
  <form action="/conditions/<%= @prize_id %>/create" method="post">
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Key number</label>
      <div class="col-sm-10">
        <input type="number" class="form-control" name="number">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">After subscriber number</label>
      <div class="col-sm-10">
        <input type="number" class="form-control" name="after_num">
      </div>
    </div>
    <fieldset class="form-group">
      <div class="row">
        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input" type="radio" name="condition_type" id="condition_type1" value="S" checked>
            Win prize subscriber with specific number
          </label>
        </div>
        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input" type="radio" name="condition_type" id="condition_type2" value="M">
            Wins prize subscribers multiples of key number
          </label>
        </div>
      </div>
    </fieldset>
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Create!</button>
      </div>
    </div>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UvoPrizeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <strong><%= link_to "UvoPrizeApp", root_path, class: "navbar-brand" %></strong>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <% if user_signed_in? %>
              <ul class="nav navbar-nav">
                <li class="<%= 'active' if current_page?(prizes_path) %>">
                  <%= link_to "Prize Management", prizes_path %>
                </li>
              </ul>
            <% end %>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li class="<%= 'active' if current_page?(edit_user_registration_path) %>">
                  <%= link_to current_user.email, edit_user_registration_path %>
                </li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <li class="<%= 'active' if current_page?(new_user_registration_path) %>">
                  <%= link_to "Sign Up", new_user_registration_path %>
                </li>
                <li class="<%= 'active' if current_page?( new_user_session_path) %>">
                  <%= link_to "Sign In", new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
          <% flash.each do |type, message| %>
            <div class="alert alert-<%= flash_class(type.to_sym) %> alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= message %>
            </div>
          <% end %>
          <br>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/prizes/edit.html.erb
<h1>Edit a Prize</h1>
<form action="/prizes/<%= @prize[:id] %>/update" method="post">
  <div class="form-group">
    <label>Title</label>
    <input type="text" class="form-control" name="title" value="<%= @prize[:title] %>">
  </div>
  <div class="form-group">
    <label>Description</label>
    <input type="text" class="form-control" name="description" value="<%= @prize[:description] %>">
  </div>
  <div class="form-group">
    <label class="col-sm-2 col-form-label">Existences</label>
    <div class="col-sm-2">
      <input type="number" class="form-control" name="existences" value="<%= @prize[:existences] %>">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">
    Edit
  </button>
</form>

app/views/prizes/index.html.erb
<div class="jumbotron">
  <h1>Uvo Prize App</h1>
  <p>
    <a class="btn btn-primary btn-lg" href=<%=new_prize_path%> role="button">Create one prize</a>
  </p>
</div>
<hr>
<% @prizes.each do |prize| %>
<blockquote class="blockquote">
  <p class="h4"><strong>Title: <%= prize[:title] %></strong></p>
  <p class="h4">Description: <%= prize[:description] %></p>
  <p class="h3">Number of existences: <%= prize[:existences] %></p>
  <% if prize.conditions %>
    <% prize.conditions.each do |condition| %>
      <footer>
      <% case condition[:condition_type] %>
        <% when "M" %>
          Wins prize subscribers multiples of <%= condition[:number] %> after <%= condition[:after_num] %> subscribers.
        <% when "S" %>
          Wins prize specific Subscriber number <%= condition[:number] %> after <%= condition[:after_num] %> subscribers.
      <% end %>
      <a href="/conditions/<%= condition[:id] %>/delete" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Remove</a>
      </footer>
    <% end %>
  <% end %>
</blockquote>
<a href="/conditions/<%= prize[:id] %>/new" class="btn btn-default">
  <span class="glyphicon glyphicon-plus-sign"></span> Add new condition
</a>
<a href="/prizes/<%= prize[:id] %>/edit" class="btn btn-default">
  <span class="glyphicon glyphicon-edit"></span> Edit
</a>
<a href="/prizes/<%= prize[:id] %>/delete" class="btn btn-danger">
  <span class="glyphicon glyphicon-remove"></span> Delete
</a>
<hr>
<% end %>

app/views/prizes/new.html.erb
<h1>Create a Prize</h1>
<form action="/prizes" method="post">
  <div class="form-group">
    <label>Title</label>
    <input type="text" class="form-control" name="title">
  </div>
  <div class="form-group">
    <label>Description</label>
    <input type="text" class="form-control" name="description">
  </div>
  <div class="form-group">
    <label class="col-sm-2 col-form-label">Existences</label>
    <div class="col-sm-2">
      <input type="number" class="form-control" name="existences">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">
    Create!
  </button>
</form>

app/views/subscribers/home.html.erb
<div class="starter-template">
  <h1>Uvo Prize App</h1>
  <p class="lead">Welcome!, do you want to take part in our great drawing of prizes?, 
      it is very easy, you just have to subscribe your e-mail and you will participate immediately, 
      in addition we are going to send you an e-mail with all the available prizes. 
      You can only participate once a day. What are you waiting for?, subscribe now!.</p>
</div>

<div class="row">
  <div class="text-center">
    <div class="col-md-4 col-md-offset-4">
        <form action=<%= subscriber_path %> method="post">
          <div class="form-group">
            <label>Email address</label>
            <input type="email" class="form-control" name="email">
          </div>
          <button type="submit" class="btn btn-primary">
            Subscribe!
          </button>
        </form>
    </div>
  </div>
</div>